create schema if not exists razreshenobot;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'request_status') then
    create type public.request_status as enum ('open', 'closed', 'cancelled');
  end if;
  if not exists (select 1 from pg_type where typname = 'delivery_method') then
    create type public.delivery_method as enum ('manual', 'username');
  end if;
  if not exists (select 1 from pg_type where typname = 'payment_status') then
    create type public.payment_status as enum ('pending', 'paid', 'canceled');
  end if;
  if not exists (select 1 from pg_type where typname = 'document_tariff') then
    create type public.document_tariff as enum ('149', '199');
  end if;
  if not exists (select 1 from pg_type where typname = 'delivery_status') then
    create type public.delivery_status as enum ('scheduled', 'sent', 'failed');
  end if;
end $$;

create table if not exists razreshenobot.users (
  id bigint generated by default as identity primary key,
  tg_user_id bigint not null unique,
  timezone text,
  timezone_source text,
  timezone_updated_at timestamptz,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists razreshenobot.requests (
  id bigint generated by default as identity primary key,
  user_id bigint not null references razreshenobot.users(id) on delete cascade,
  status public.request_status not null default 'open',
  recipient_name text,
  selected_variant_idx integer,
  delivery_method public.delivery_method,
  delivery_username text,
  initiator_timezone text,
  initiator_timezone_source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  closed_at timestamptz
);

create index if not exists idx_requests_user_id on razreshenobot.requests(user_id);
create index if not exists idx_requests_status on razreshenobot.requests(status);

create table if not exists razreshenobot.payments (
  id bigint generated by default as identity primary key,
  request_id bigint not null references razreshenobot.requests(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  amount numeric(10,2) not null,
  status public.payment_status not null default 'pending',
  paid_at timestamptz,
  provider_payment_charge_id text not null unique,
  created_at timestamptz not null default now()
);

create index if not exists idx_payments_request_id on razreshenobot.payments(request_id);

create table if not exists razreshenobot.documents (
  id bigint generated by default as identity primary key,
  request_id bigint not null references razreshenobot.requests(id) on delete cascade,
  tariff public.document_tariff not null,
  initiator_name text not null,
  render_params jsonb not null default '{}'::jsonb,
  final_file_id text,
  created_at timestamptz not null default now(),
  unique (request_id, tariff)
);

create index if not exists idx_documents_request_id on razreshenobot.documents(request_id);

create table if not exists razreshenobot.deliveries (
  id bigint generated by default as identity primary key,
  document_id bigint not null references razreshenobot.documents(id) on delete cascade,
  scheduled_at timestamptz not null,
  delivery_method public.delivery_method not null,
  recipient_username text,
  status public.delivery_status not null default 'scheduled',
  attempts integer not null default 0,
  locked_at timestamptz,
  lock_owner text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  unique (document_id)
);

create index if not exists idx_deliveries_due on razreshenobot.deliveries(status, scheduled_at);
